In [61]:
import pandas as pd
import numpy as np

### Section A: Data Structures & Control Structures

In [21]:
# 1.	Create a list of 5 integers. Perform and print the result of the following operations: 
# append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
Data = [10,20,30,40,50]
Data.append(60)
print("List after appending:", Data)
Data.extend([11,12])
print("List after extending:", Data)
Data.insert(1,300)
print("List after inserting:", Data)
Data.remove(300)
print("List after removing:", Data)
Data.pop(7)
print("List after poping:", Data)
print("index of 11:", Data.index(11))
print("count of 11:", Data.count(11))
Data.sort()
print("List of Shorting:", Data)
Data.reverse()
print("List of Reversing:", Data)
Data.clear()
print("Clean the list:", Data)

List after appending: [10, 20, 30, 40, 50, 60]
List after extending: [10, 20, 30, 40, 50, 60, 11, 12]
List after inserting: [10, 300, 20, 30, 40, 50, 60, 11, 12]
List after removing: [10, 20, 30, 40, 50, 60, 11, 12]
List after poping: [10, 20, 30, 40, 50, 60, 11]
index of 11: 6
count of 11: 1
List of Shorting: [10, 11, 20, 30, 40, 50, 60]
List of Reversing: [60, 50, 40, 30, 20, 11, 10]
Clean the list: []

In [24]:
# 2. Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
students = ("Amit", "Neha", "Rahul")
print(students)
students[1]="Priya"

# Explanation:
# This happens because tuples are immutable in Python.
# Immutability means that once a tuple is created, its elements cannot be changed, added, or removed.

('Amit', 'Neha', 'Rahul')

TypeError: 'tuple' object does not support item assignment

In [27]:
# 3. Create a set of integers with some duplicate values. Print the set and explain the output.
numbers = {1, 2, 3, 4, 2, 3, 5}
print(numbers)

# Explanation:
# A set in Python automatically removes duplicate values.
# Even though 2 and 3 were added more than once, they appear only once in the output.
# This happens because sets store unique elements only and do not allow duplicates.

{1, 2, 3, 4, 5}

In [31]:
# 4. Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
Person = {
    "Name" : "Harshal",
    "Age" : 24,
    "City" : "Banglore"
}

Person["Age"] = 26
Person["Email"] = "harshal2@gmail.com"
print(Person)

{'Name': 'Harshal', 'Age': 26, 'City': 'Banglore', 'Email': 'harshal2@gmail.com'}

In [38]:
# 5. Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

age = int(input("Put the age:"))

if age >= 18:
    print("The person is eligible to vote.")
else:
    print("The person is not eligible to vote.")

Put the age: 22

The person is eligible to vote.

In [47]:
# 6. Given a 'marks' variable, print the grade:
# 90 and above: 'A'
# 75–89: 'B'
# 50–74: 'C'
# Below 50: 'Fail'

marks =int(input("Enter the marks:" ))
if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 50:
    grade = "C"
else:
    grade = "Fail"

print("Grade:", grade)

Enter the marks: 60

Grade: C

In [53]:
# 7. Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

number = int(input("Give a number:"))

if number >= 0 and number % 2 == 0:
    num = "Number is positive & even"
elif number >= 0 and number % 2 != 0:
    num = "Number is positive but odd"
elif number < 0 and number % 2 == 0:
    num = "Number is nagative & even"
elif number < 0 and number % 2 != 0:
    num = "Number is nagative but odd"
elif number == 0:
    num = "Number is zero"

print("Number:", num)

Give a number: -15

Number: Number is nagative but odd

### Section B: Numpy

In [57]:
# 8.Create:
# A scalar using np.array(5)
# A 1D array with values 1 to 5
# A 2D array (2x3) with values from 10 to 60 in steps of 10

scalar = np.array(5)
print(scalar)
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])
print(array_2d)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]

In [58]:
# 9. Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

random_array = np.random.randint(0, 100, size=(4, 4))
print(random_array)

[[77 44 24 15]
 [69 18 75 27]
 [44 65 16 80]
 [78 59 49 13]]

In [59]:
# 10. Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

arr_2d = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])
df = pd.DataFrame(arr_2d, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

### Section C: Exploring Pandas

In [63]:
# 11. Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
# Use .info(), .describe()
# Select 'Name' and 'City' columns
# Drop 'City' column
# Fill any missing values in 'Salary' column with the mean
# Remove any duplicate rows

Dataset = {
    'Name': ['Kavee', 'Anu', 'Sriman', 'Karti', 'Mohinth', 'Srinath', 'Kiran', 'Roshu', 'shahana', 'Manju'],
    'Age': [25, 30, 35, 40, 45, 50, 55, 60, 65, 70],
    'City': ['BTM', 'Cbe', 'Thrichy', 'Cbe', 'BTM', 'Cbe', 'Indra Nagar', 'Karamadai', 'Tirupur', 'Bangalore'],
    'Salary': [50000, 60000, 70000, 80000, 90000, None, 110000, 120000, 130000, 140000]
}
Data = pd.DataFrame(Dataset)

In [67]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [68]:
Data.describe()

             Age         Salary
count  10.000000       9.000000
mean   47.500000   94444.444444
std    15.138252   32058.973436
min    25.000000   50000.000000
25%    36.250000   70000.000000
50%    47.500000   90000.000000
75%    58.750000  120000.000000
max    70.000000  140000.000000

In [70]:
Data[["Name","City"]]

      Name         City
0    Kavee          BTM
1      Anu          Cbe
2   Sriman      Thrichy
3    Karti          Cbe
4  Mohinth          BTM
5  Srinath          Cbe
6    Kiran  Indra Nagar
7    Roshu    Karamadai
8  shahana      Tirupur
9    Manju    Bangalore

In [72]:
Data.drop("City", axis=1, inplace=True)

In [74]:
Data.head()

      Name  Age   Salary
0    Kavee   25  50000.0
1      Anu   30  60000.0
2   Sriman   35  70000.0
3    Karti   40  80000.0
4  Mohinth   45  90000.0

In [75]:
Data.fillna(Data['Salary'].mean(),inplace=True)

In [76]:
Data

      Name  Age         Salary
0    Kavee   25   50000.000000
1      Anu   30   60000.000000
2   Sriman   35   70000.000000
3    Karti   40   80000.000000
4  Mohinth   45   90000.000000
5  Srinath   50   94444.444444
6    Kiran   55  110000.000000
7    Roshu   60  120000.000000
8  shahana   65  130000.000000
9    Manju   70  140000.000000

In [77]:
Data.drop_duplicates(inplace=True)
Data

      Name  Age         Salary
0    Kavee   25   50000.000000
1      Anu   30   60000.000000
2   Sriman   35   70000.000000
3    Karti   40   80000.000000
4  Mohinth   45   90000.000000
5  Srinath   50   94444.444444
6    Kiran   55  110000.000000
7    Roshu   60  120000.000000
8  shahana   65  130000.000000
9    Manju   70  140000.000000