In [1]:
import pandas as pd
import numpy as np

In [2]:
Billing = pd.read_csv('Billing_Data.csv')
Patient = pd.read_csv('Patient_Data.csv')

In [3]:
Billing.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [4]:
Patient.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [5]:
Patient.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [6]:
Patient.shape

(6, 7)

In [7]:
Billing.shape

(5, 3)

In [8]:
Patient[['PatientID','Department','Doctor','BillAmount']]

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [9]:
Patient.drop(columns=['ReceptionistID','CheckInTime'],inplace=True)

In [10]:
Patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [11]:
Patient.groupby('Department')['BillAmount'].sum()

Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

In [12]:
Patient = Patient.drop_duplicates()
Patient.duplicated().sum()

np.int64(0)

In [13]:
Patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

In [14]:
Patient.isnull().sum()

PatientID     0
Name          0
Department    0
Doctor        0
BillAmount    2
dtype: int64

In [15]:
Patient['BillAmount']= Patient['BillAmount'].fillna(Patient['BillAmount'].mean()).round(1)
Patient

C:\Users\SHAH HARSHAL\AppData\Local\Temp\ipykernel_8280\2781618218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Patient['BillAmount']= Patient['BillAmount'].fillna(Patient['BillAmount'].mean()).round(1)

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      6233.3
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      6233.3

In [16]:
Merge = pd.merge(Patient,Billing,on='PatientID')
Merge

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000,3000
1,102,Bob,Neurology,Dr. John,6233.3,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.0,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.3,1000,4000

In [17]:
Patient

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John      6233.3
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose      6233.3

In [18]:
New_patient_data = {
    "PatientID":['106',"107"],
	'Name':['Kavee','Sriman'],
	'Department':['Cardiology','Neurology'],
	'Doctor':['Dr. Smith','Dr. John'],
	'BillAmount':['10000','11000'],
}

In [19]:
New_patient_df=pd.DataFrame(New_patient_data)
Merge = pd.concat([Patient,New_patient_df],axis = 0,ignore_index=True)
Merge

  PatientID     Name   Department     Doctor BillAmount
0       101    Alice   Cardiology  Dr. Smith     5000.0
1       102      Bob    Neurology   Dr. John     6233.3
2       103  Charlie  Orthopedics    Dr. Lee     7500.0
3       104    David   Cardiology  Dr. Smith     6200.0
4       105      Eva  Dermatology   Dr. Rose     6233.3
5       106    Kavee   Cardiology  Dr. Smith      10000
6       107   Sriman    Neurology   Dr. John      11000

In [20]:
merged_final = pd.concat([Merge,Billing[['InsuranceCovered','FinalAmount']]],axis=1)

In [21]:
merged_final

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.3,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.3,1000.0,4000.0
5,106,Kavee,Cardiology,Dr. Smith,10000,NaN,NaN
6,107,Sriman,Neurology,Dr. John,11000,NaN,NaN

In [22]:
merged_final['InsuranceCovered']= merged_final['InsuranceCovered'].fillna(merged_final['InsuranceCovered'].mean())
merged_final['FinalAmount']= merged_final['FinalAmount'].fillna(merged_final['FinalAmount'].mean())

In [23]:
merged_final

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.0,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.3,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.0,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.3,1000.0,4000.0
5,106,Kavee,Cardiology,Dr. Smith,10000,2000.0,3740.0
6,107,Sriman,Neurology,Dr. John,11000,2000.0,3740.0